name: CI
on:
  push:
    branches:
    - master
    - musl
    tags:
    - "v*"
  pull_request:

jobs:
  generate-native-launchers:
    name: Upload musl native launcher 
    runs-on: ubuntu-latest
    container: ghcr.io/graalvm/graalvm-ce:21.1.0
    steps:
      - run: microdnf install git
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - uses: coursier/cache-action@v6.2
      - uses: coursier/setup-action@v1
        with:
          jvm: 8
      - name: Create result directory
        run: |
          RESULT_DIR=$PWD/staticlibs
          mkdir $RESULT_DIR
          echo $RESULT_DIR/bin >> $GITHUB_PATH
          echo "result_dir=$RESULT_DIR" >> $GITHUB_ENV
      - name: Install musl
        run: |
          curl -L -o musl.tar.gz https://musl.libc.org/releases/musl-1.2.1.tar.gz
          mkdir musl
          tar -xvzf musl.tar.gz -C musl --strip-components 1
          cd musl
          ./configure --disable-shared --prefix=${{ env.result_dir }}
          make
          make install
      - name: Install zlib
        run: |
          CC=musl-gcc
          curl -L -o zlib.tar.gz https://zlib.net/zlib-1.2.11.tar.gz
          mkdir zlib
          tar -xvzf zlib.tar.gz -C zlib --strip-components 1
          cd zlib
          ./configure --static --prefix=${{ env.result_dir }}
          make
          make install
      - name: Install libstdc++
        run: cp /usr/lib/gcc/x86_64-redhat-linux/8/libstdc++.a ${{ env.result_dir }}/lib
      - name: Copy artifacts
        run: ./mill -i copyLauncher artifacts/
        env:
          NATIVE_IMAGE_LIBC: musl
      - uses: actions/upload-artifact@v2.2.3
        with:
          name: launchers
          path: artifacts/
          if-no-files-found: error
          retention-days: 2