name: CI
on:
  push:
    branches:
    - master
    - musl
    tags:
    - "v*"
  pull_request:

jobs:
  generate-native-launchers:
    name: Upload musl native launcher 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - uses: coursier/cache-action@v6.2
      - uses: coursier/setup-action@v1
        with:
          jvm: 8
      - name: Copy artifacts
        run: ./mill -i copyLauncher artifacts/
        env:
          NATIVE_IMAGE_STATIC: true
      - uses: actions/upload-artifact@v2.2.3
        with:
          name: launchers
          path: artifacts/
          if-no-files-found: error
          retention-days: 2