name: CI
on:
  push:
    branches:
    - master
    - static-binary
    tags:
    - "v*"
  pull_request:

jobs:
  generate-native-launchers:
    name: Upload native launcher ${{ matrix.OS }}
    runs-on: ${{ matrix.OS }}
    strategy:
      fail-fast: false
      matrix:
        OS: ["ubuntu-latest", "windows-2016", "macos-latest"]
        static: [true, false]
        exclude:
          - os: windows-2016
            static: true
          - os: macos-latest
            static: true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - uses: coursier/cache-action@v6.2
      - uses: coursier/setup-action@v1
        with:
          jvm: 8
      - name: Copy artifacts
        run: ./mill -i copyLauncher artifacts/
        env:
          NATIVE_IMAGE_STATIC: ${{ matrix.static }}
      - uses: actions/upload-artifact@v2.2.3
        with:
          name: launchers
          path: artifacts/
          if-no-files-found: error
          retention-days: 2
